site_name: MLOps @ äon intelligence
nav:
  - Home: index.md
  - Setup: setup.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.tabs
    - navigation.top