site_name: "MLOps: Modeling, Deploying and Monitoring @ äon intelligence"
nav:
  - Home: index.md
  - Project Management: project_management.md
  - Ethics: ethics.md
  - Setup: setup.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
